(()=>{
var
    db=new syntaxHighlighter.Database('js'),
    matchingRules={
        comment:[
            {
                regex:/^(\/\/.*\n)/,
            },{
                regex:/^(\/\*(?:.|\n)*\*\/)/,
            }
        ],
        string:[
            {
                regex:/^('(?:[^'\\]|\\.)*')/,
            },{
                regex:/^("(?:[^"\\]|\\.)*")/,
            },{
                regex:/^(`(?:[^`\\]|\\.)*`)/,
            }
        ],
        operator:{
            regex:/^([!%&\(\)\*\+\,\-\.\/\:;\<=\>\?\[\]\^\{\|\}\~])/,
        },
        number:{
            regex:/^([0-9]+(?:\.[0-9]+)?)/
        },
        identifier:{
            regex:/^([A-Z_a-z]+)/,
            containKeywords:[
                'keyword',
                'library',
            ]
        },
        keyword:{
            active:false,
        },
        library:{
            active:false,
        },
    }
syntaxHighlighter.highlightJs=highlightJs
async function highlightJs(source){
    await db.require([
        'keyword',
        'library',
    ])
    matchingRules.keyword.keywords=db.data.keyword
    matchingRules.library.keywords=db.data.library
    return syntaxHighlighter.highlight(
        syntaxHighlighter.analyze(matchingRules,source)
    )
}
})()
